continuumVersion=3.1.0-SNAPSHOT

allureVersion=2.29.1
aspectJVersion=1.9.22.1
apacheCommonsLangVersion=3.20.0
apacheCommonsTextVersion=1.15.0
commonsIoVersion=2.21.0
failsafeVersion=3.3.2
groovyVersion=4.0.26
igniteVersion=2.18.0
jakartaAnnotationVersion=3.0.0
jCacheApiVersion=1.0.0
jreleaserVersion=1.21.0
lombokPluginVersion=9.1.0
otelBomVersion=1.57.0
otelInstrumentationBomVersion=2.23.0
springBootVersion=4.0.2
springDependencyManagementVersion=1.1.7
vertxVersion=5.1.4
vertxStompLiteVersion=6.0.0
